### PR TITLE
Example API Connector implementation

### PR DESCRIPTION
**Pull request by Cruikshanks**
https://github.com/DEFRA/sroc-tcm-admin/pull/192

This is an example of how the work in PR #192 could be reworked to use modules. Our blocker was testing, and the fact we only really knew how to go about it using rspec. So we needed [RSpec integrated first](https://github.com/DEFRA/sroc-tcm-admin/pull/267) before we could tackle this example.

### CODE REVIEW

**Comment by Cruikshanks** [comment]
I've double-checked the Simplecov reports locally and I'm happy the new code does have full coverage hence I'm ignoring SonarCloud on this one.

**Comment by Cruikshanks** [comment]
When you are ready @StuAA78 , this is ready for review and approval 😁

**Review by StuAA78 — APPROVED** [review]
Looks good! 👍

**Comment by Cruikshanks** [comment]
Same code, now just ready to be merged to `master` 😁 !

**Review by StuAA78 — APPROVED** [review]
All good 😁

**Pull request merged**
